server:
  port: 9000
javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true
  # Enable monitoring of Spring services and controllers (optional, default: true)
  spring-monitoring-enabled: true
  init-parameters:
    # log http requests:
    log: true
    # to exclude images, css, fonts and js urls from the monitoring:
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # to aggregate digits in http requests:
    #http-transform-pattern: \d+
    # to add basic auth:
    #authorized-users: admin:pwd
    # to change the default storage directory:
    #storage-directory: /tmp/javamelody
    # to change the default "/monitoring" path:
    #monitoring-path: /admin/performance